
#General Config Section. See https://readme.firstdarkdev.xyz/simple-rpc/introduction/
[general]
	#The Application ID of the Discord App to use
	applicationID = 1208231554585993216
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Enable/Disable the in game config screen. ONLY AVAILABLE WHEN CLOTH CONFIG IS INSTALLED!
	configScreen = true
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Internal Version Number. NO TOUCHY!
	version = 16

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true
	#The first line of text under the app name
	description = "SUNSI is loading"
	#The second line of text under the app name
	state = "Game Starting..."
	#The Asset ID of the image to display as the large image
	largeImageKey = "sunsiblack"
	#The text that gets displayed when the large image is hovered
	largeImageText = "RELEASE V2"
	#The Asset ID of the image to display as the small image
	smallImageKey = ""
	#The text that gets displayed when the small image is hovered
	smallImageText = "You'll be there soon..."
	#The buttons to display on Discord
	buttons = []

#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on SUNSI"
	#The seconds line of text under the app name
	state = "In menu"
	#The Asset ID of the image to display as the large image
	largeImageKey = "sunsiblack"
	#The text that gets displayed when the large image is hovered
	largeImageText = "RELEASE V2"
	#The Asset ID of the image to display as the small image
	smallImageKey = "sunsismall"
	#The text that gets displayed when the small image is hovered
	smallImageText = "You'll be there soon..."
	#The buttons to display on Discord
	buttons = []

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on SUNSI"
	#The second line of text under the app name
	state = "Selecting a server..."
	#The Asset ID of the image to display as the large image
	largeImageKey = "sunsiblack"
	#The text that gets displayed when the large image is hovered
	largeImageText = "RELEASE V2"
	#The Asset ID of the image to display as the small image
	smallImageKey = ""
	#The text that gets displayed when the small image is hovered
	smallImageText = "You'll be there soon..."
	#The buttons to display on Discord
	buttons = []

#The Realms Screen event
[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on SUNSI"
	#The second line of text under the app name
	state = "This doesn't look like sunsi's world?"
	#The Asset ID of the image to display as the large image
	largeImageKey = "sunsiblack"
	#The text that gets displayed when the large image is hovered
	largeImageText = "RELEASE V2"
	#The Asset ID of the image to display as the small image
	smallImageKey = ""
	#The text that gets displayed when the small image is hovered
	smallImageText = "You'll be there soon..."
	#The buttons to display on Discord
	buttons = []

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on SUNSI"
	#The second line of text under the app name
	state = "Joining Game..."
	#The Asset ID of the image to display as the large image
	largeImageKey = "sunsiwhite"
	#The text that gets displayed when the large image is hovered
	largeImageText = "RELEASE V2"
	#The Asset ID of the image to display as the small image
	smallImageKey = ""
	#The text that gets displayed when the small image is hovered
	smallImageText = "You'll be there soon..."
	#The buttons to display on Discord
	buttons = []

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on SUNSI"
	#The second line of text under the app name
	state = "Playing alone."
	#The Asset ID of the image to display as the large image
	largeImageKey = "sunsipurple"
	#The text that gets displayed when the large image is hovered
	largeImageText = "RELEASE V2"
	#The Asset ID of the image to display as the small image
	smallImageKey = ""
	#The text that gets displayed when the small image is hovered
	smallImageText = "You'll be there soon..."
	#The buttons to display on Discord
	buttons = []

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on SUNSI"
	#The second line of text under the app name
	state = "Sharing resources with friends!"
	#The Asset ID of the image to display as the large image
	largeImageKey = "sunsipurple"
	#The text that gets displayed when the large image is hovered
	largeImageText = "RELEASE V2"
	#The Asset ID of the image to display as the small image
	smallImageKey = "sunsismall"
	#The text that gets displayed when the small image is hovered
	smallImageText = "You'll be there soon..."
	#The buttons to display on Discord
	buttons = []

#The Realms Game Event
[realms]
	#Enable/Disable the Realms Game Event
	enabled = true
	#The first line of text under the app name
	description = "Playing on SUNSI"
	#The second line of text under the app name
	state = "Playing on a Realm."
	#The Asset ID of the image to display as the large image
	largeImageKey = "sunsiblack"
	#The text that gets displayed when the large image is hovered
	largeImageText = "RELEASE V2"
	#The Asset ID of the image to display as the small image
	smallImageKey = ""
	#The text that gets displayed when the small image is hovered
	smallImageText = "%realmdescription%"
	#The buttons to display on Discord
	buttons = []

#Fallback event for disabled events
[generic]
	#The first line of text under the app name
	description = "Playing on SUNSI"
	#The second line of text under the app name
	state = ""
	#The Asset ID of the image to display as the large image
	largeImageKey = "sunsiblack"
	#The text that gets displayed when the large image is hovered
	largeImageText = "RELEASE V2"
	#The Asset ID of the image to display as the small image
	smallImageKey = ""
	#The text that gets displayed when the small image is hovered
	smallImageText = "You'll be there soon..."
	#The buttons to display on Discord
	buttons = []

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = false

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "overworld"
		#The first line of text under the app name
		description = "%player% is in The Overworld"
		#The second line of text under the app name
		state = ""
		#The Asset ID of the image to display as the large image
		largeImageKey = "overworld"
		#The text that gets displayed when the large image is hovered
		largeImageText = "In the Overworld"
		#The Asset ID of the image to display as the small image
		smallImageKey = ""
		#The text that gets displayed when the small image is hovered
		smallImageText = "You'll be there soon..."
		#The buttons to display on Discord
		buttons = []

	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "the_nether"
		#The first line of text under the app name
		description = "%player% is in The Nether"
		#The second line of text under the app name
		state = ""
		#The Asset ID of the image to display as the large image
		largeImageKey = "nether"
		#The text that gets displayed when the large image is hovered
		largeImageText = "In the Nether"
		#The Asset ID of the image to display as the small image
		smallImageKey = ""
		#The text that gets displayed when the small image is hovered
		smallImageText = "You'll be there soon..."
		#The buttons to display on Discord
		buttons = []

	[[dimension_overrides.dimensions]]
		#The name of the Dimension/Biome to override. FORMAT: modid:dimension or modid:biome
		name = "the_end"
		#The first line of text under the app name
		description = "%player% is in The End"
		#The second line of text under the app name
		state = ""
		#The Asset ID of the image to display as the large image
		largeImageKey = "end"
		#The text that gets displayed when the large image is hovered
		largeImageText = "In the End"
		#The Asset ID of the image to display as the small image
		smallImageKey = ""
		#The text that gets displayed when the small image is hovered
		smallImageText = "You'll be there soon..."
		#The buttons to display on Discord
		buttons = []